name: Feature request
description: An idea for a new module, integration or improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What would you like to do?
      description: Describe the use case rather than the solution.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: How could it work?
  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      options:
        - label: I would like to implement this myself
